### ISSUE TITLE
Nomenclature is unclear

### ISSUE THREAD

**Issue by flatsiedatsie** [mozilla-iot/virtual-things-adapter#29]
When adding a new virtual thing, the UX asks to select an "@type", and then refers to the schema to select one.

Except in the schema overview the @type isn't really mentioned (except in the example). Perhaps ask users to select a _capability_ from that page instead?

**Comment by madb1lly** [comment]
I agree. 

After discussing a related issue with @mrstegeman on IRC he shared the following examples and explanation (which I've summarised):
Example screenshots: https://imgur.com/a/DasWqNu
Properties have to be explicitly defined even if they are stated as required on the schemas page (https://iot.mozilla.org/schemas/) because one thing may have multiple schemas some or all of which may have optional properties.

**Comment by mrstegeman** [comment]
From the intro on the linked schemas page:

> This web page describes a repository of Web of Things capability schemas to be used as optional semantic markup in Web Thing Descriptions.
>
> To use a schema from this repository, a Thing Description must define a `@context` of `"https://iot.mozilla.org/schemas"`, define one or more device capability types as a top level `@type` array and define at least the required properties, actions and events for those capabilities with an appropriate `@type` annotation.

**Comment by madb1lly** [comment]
Thanks @mrstegeman.
