### ISSUE TITLE
Question: How to add virtual device

### ISSUE THREAD

**Issue by svrooij** [mozilla-iot/virtual-things-adapter#8]
Is there some kind of wizard, or should i just send an http call somewhere to get a virtual device?

**Comment by mrstegeman** [comment]
Do you mean create a brand new virtual device, or add an existing one to the UI?

**Comment by svrooij** [comment]
I would like to add an OnOfSwitch to the UI.

**Comment by Rudower** [comment]
Hi, I'd like to know how may I interact with this "Virtual on/off switch" from the internet. How would the http call look like? Any url to be navigated to from a browser to switch on and off? 

Thx a lot!

**Comment by mrstegeman** [comment]
@Rudower You have to send a PUT request. For an example script, [see here](https://github.com/mozilla-iot/curl-examples/blob/master/set-property.sh).

**Comment by Rudower** [comment]
Hi mrstegeman. Thanks for your quick response. 

I've managed to launch PUT Rest requests,  but I get the following unsuccessful response: 

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Error</title>
</head>
<body>
<pre>Cannot PUT /myvirtualswitch</pre>
</body>
</html>

I get exactly the same whether I use authentication with my user/pwd, or when I leave these fields blank. 

Just to make it clear to myself, I'll post here what I do step by step, so that you can detect where my mistake is: 

1) I add add-on "HTTPS on/off", enable it and configure it with url https://xxx.mozilla-iot.org/myvirtualswitch

2) I add add-on "Virtual Things" and enable it (I really don't quite catch where the virtual thing is linked to the previous url)

3) I go to things menu, and add a new item. I choose a "Virtual on/off switch"

4) I launch a Rest PUT request to the given url with and without authentication, and without passing on to it any header nor parameter. I get always the same unsuccessful message from above. 

Am I missing anything? Thx again!

**Comment by mrstegeman** [comment]
> 1. I add add-on "HTTPS on/off", enable it and configure it with url https://xxx.mozilla-iot.org/myvirtualswitch

This add-on is something completely different. You don't need this for virtual devices.

> 2. I add add-on "Virtual Things" and enable it (I really don't quite catch where the virtual thing is linked to the previous url)

This is the proper add-on.

> 3. I go to things menu, and add a new item. I choose a "Virtual on/off switch"

Good.

> 4. I launch a Rest PUT request to the given url with and without authentication, and without passing on to it any header nor parameter. I get always the same unsuccessful message from above.

If you're using the curl examples I referenced, you'll first need to use the `login.sh` script. This will get your JSON Web Token (JWT) which is used for authentication in the other requests.

For the `login.sh` script, you will enter the following info:
1. URL: `https://xxx.mozilla-iot.org`
2. Email: the email you used to create your user account
3. Password: the password you set for your user account

After doing this, you will use `set-property.sh` as such:
```bash
./set-property.sh virtual-things-3 on false
```

What this translates to is essentially:
```bash

curl -H "Authorization: Bearer ${JWT}" \
  -H "Content-Type: application/json" \
  -H "Accept: application/json" \
  -X PUT -d '{"on": false}' \
  https://xxx.mozilla-iot.org/things/virtual-things-3/properties/on
```

**Comment by Rudower** [comment]
Hi again mrstegeman... You mention that you reference two shell scripts: login.sh and set-property.sh

I've searched for these two scripts in your code files, in the comments, and on all of your Github virtual-things-adapter page, but I didn't find them...

**Comment by Rudower** [comment]
This is great! Thanks a lot! I've managed to run the scripts, but just one last question: 

Can the user/pwd for login.sh be a secondary user (I mean, not the main user with which I created the account, but another one I've created specifically for this automation)? 

The fact is that login.sh shows an strange behaviour after being run (starts by itself again from the very beginning asking for url), and the execution of set-property.sh has the same result (restarts login.sh asking for url)

**Comment by mrstegeman** [comment]
It shouldn’t matter what user you enter, as all users currently have all the same permissions.

**Comment by Rudower** [comment]
I have some new hints of why it doesn't work. I removed the "> /dev/null" at the end of set-property.sh, so as to have some feedback from my gateway, and whatever I do with this virtual switch (on or off), I get the same message: 

<html>
<head><title>301 Moved Permanently</title></head>
<body bgcolor="white">
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx/1.14.1</center>
</body>
</html>

I don't know what this really means... But doesn't sound very successful...

**Comment by Rudower** [comment]
And by the way, I got it to work thanks to your great help. I love github (and the community)

**Comment by mrstegeman** [comment]
`virtual-things-3` is the ID of the thing. It is in the thing description. The virtual-things-adapter has a fixed set of IDs that will never change.
